---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: package
    run_list:
      - recipe[mosh]
  - name: source
    run_list:
      - recipe[build-essential]
      - recipe[mosh]
    attributes:
      mosh:
        install_type: source